### PR TITLE
Pull Requests are a sign of social activity!

### PR DESCRIPTION
**Pull request by fate83**
Hi halfdan,

I hereby want to point out, that pull requests can indeed pull two individuals closer to each other. For a good reason I want you to pull my request. My commit adds a full new line to your awesome repository. This line is for free and keeps the good work going. It will increase the overall greatness of this file even further. So you see there is no reason why you should not merge this great line into your projekt.

Yours

fate83

PS: ^^

### CODE REVIEW

**Comment by halfdan** [comment]
@fate83 Dear fate, I really welcome your enthusiasm in helping is awesome project! Can you please add a unit test to your pull request so I can trust the commit not to break anything for our 12 billion users?

**Comment by fate83** [comment]
@halfdan after several thousands of working hours, 5 euro pallets full of Club Mate (TM) the most awesome tests were written for the most awesome project in the world. I therefore feel confident that the tests will indeed fulfill the strict test conditions which they have to satisfy. All the users will be pleased, too, because they now can be dead certain that they will get the best goddamn software  in the history of mankind.

**Comment by halfdan** [comment]
Dear @fate83, I am still not sure whether I should press the green merge button or close this pull request. While your tests will certainly satisfy the strict foobar quality assurance guidelines (FQAG) and please the 5 septillion users on earth and the fifth planet of proxima centauri you have forgotten to ~~bribe~~ support me.

I would be happy to discuss further development with you over 12 euro pallets full of Club Mate (TM).

**Comment by fate83** [comment]
Oh, of course I knew I forgot something! Where should I send the ~bribe~ donation to?

**Review by fate83 — COMMENTED** [review]
I am still waiting for a review Update @halfdan

**Comment by halfdan** [comment]
Can you please add a test for the test? I'm not sure the test will pass safely without a test making sure the test passes..

**Pull request closed without merging**
